import { useParams } from "react-router-dom";
import { FaLightbulb, FaRoad, FaWater, FaSun } from "react-icons/fa";
export default function CategoryPage() {
    const properties = {
        House: [
          {
            id: 1,
            link: "https://solverwp.com/demo/react/mingrand/assets/img/product/cat-1.png",
            title: "House",
            description: "3 BHK House in Vijay Nagar, Jabalpur",
            price: "$240,000",
            status: "Ready to Move",
            propertyDetails: {
              area: "2000 sq.ft",
              configuration: "3 Bedrooms, 3 Bathrooms, 1 Balcony",
              address: "Vijay Nagar, Jabalpur",
              floors: "3 Floors",
              possession: "Immediate",
              status: "Available",
              ownership: "Freehold",
              furnishing: "Semi-Furnished",
              parking: "2 Covered",
            },
            ownerDetails: {
              name: "Rahul Sharma",
              propertiesListed: 3,
              localities: ["Vijay Nagar", "Jabalpur City"],
              phoneNumber: "9876543210",
            },
            amenities: [
              { label: "Lights" },
              { label: "Road" },
              { label: "Drainage" },
              { label: "Road Light" },
            ],
            about: {
              location: "Chowkital Lamheta Ghat Main Road",
              approval: "TNCP Approved",
              type: "Market With Shops Available",
              minimumPrice: "$24 Lakhs",
            },
            propertyId: 101,
            type: "Residential",
            propertyFor: "Sale",
            newOrResale: "New",
            tncpApproved: "Yes",
            reraNumber: "RERA1234",
            squareFeet: "2000 sq.ft",
            dimension: "40x50",
            carParking: "2 Covered",
            yearBuilt: "2010",
            facing: "East",
            flooring: "Marble",
            ageOfProperty: "10 years",
            lift: "Yes",
          },
          {
            id: 2,
            link: "https://solverwp.com/demo/react/mingrand/assets/img/product/cat-2.png",
            title: "House2",
            description: "Luxury Villa in Whitefield, Bangalore",
            price: "$1,200,000",
            status: "Ready to Move",
            propertyDetails: {
              area: "4000 sq.ft",
              configuration: "5 Bedrooms, 5 Bathrooms, 2 Balconies",
              address: "Whitefield, Bangalore",
              floors: "2 Floors",
              possession: "Immediate",
              status: "Available",
              ownership: "Freehold",
              furnishing: "Fully Furnished",
              parking: "4 Covered",
            },
            ownerDetails: {
              name: "Anil Kumar",
              propertiesListed: 5,
              localities: ["Whitefield", "Bangalore City"],
              phoneNumber: "9876543211",
            },
            amenities: [
              { label: "Swimming Pool" },
              { label: "Gym" },
              { label: "Garden" },
              { label: "Security" },
            ],
            about: {
              location: "Whitefield Main Road",
              approval: "BDA Approved",
              type: "Luxury Villa",
              minimumPrice: "$1 Million",
            },
            propertyId: 102,
            type: "Residential",
            propertyFor: "Sale",
            newOrResale: "New",
            tncpApproved: "Yes",
            reraNumber: "RERA5678",
            squareFeet: "4000 sq.ft",
            dimension: "50x80",
            carParking: "4 Covered",
            yearBuilt: "2020",
            facing: "North",
            flooring: "Hardwood",
            ageOfProperty: "4 years",
            lift: "Yes",
          },
          {
            id: 3,
            link: "https://solverwp.com/demo/react/mingrand/assets/img/product/cat-3.png",
            title: "House3",
            description: "Residential Plot in Sector 56, Noida",
            price: "$150,000",
            status: "Available",
            propertyDetails: {
              area: "3000 sq.ft",
              address: "Sector 56, Noida",
              dimensions: "60x50",
              possession: "Immediate",
              status: "Available",
              ownership: "Freehold",
              zoning: "Residential",
            },
            ownerDetails: {
              name: "Sita Devi",
              propertiesListed: 2,
              localities: ["Sector 56", "Noida City"],
              phoneNumber: "9876543212",
            },
            amenities: [
              { label: "Gated Community" },
              { label: "Park" },
              { label: "Road Access" },
            ],
            about: {
              location: "Sector 56 Main Road",
              approval: "Noida Authority Approved",
              type: "Residential Plot",
              minimumPrice: "$150,000",
            },
            propertyId: 103,
            type: "Land",
            propertyFor: "Sale",
            newOrResale: "New",
            tncpApproved: "Yes",
            reraNumber: "RERA9101",
            squareFeet: "3000 sq.ft",
            dimension: "60x50",
            yearBuilt: "N/A",
            facing: "N/A",
            flooring: "N/A",
            ageOfProperty: "N/A",
            lift: "N/A",
          },
        ],
        villa: [
          {
            id: 1,
            link: "https://solverwp.com/demo/react/mingrand/assets/img/product/villa-1.png",
            title: "Villa A",
            description: "Modern Villa in Malibu, California",
            price: "$2,500,000",
            status: "Ready to Move",
            propertyDetails: {
              area: "5000 sq.ft",
              configuration: "6 Bedrooms, 6 Bathrooms, 3 Balconies",
              address: "Malibu, California",
              floors: "2 Floors",
              possession: "Immediate",
              status: "Available",
              ownership: "Freehold",
              furnishing: "Fully Furnished",
              parking: "5 Covered",
            },
            ownerDetails: {
              name: "John Doe",
              propertiesListed: 8,
              localities: ["Malibu", "Los Angeles"],
              phoneNumber: "9876543213",
            },
            amenities: [
              { label: "Swimming Pool" },
              { label: "Home Theater" },
              { label: "Gym" },
              { label: "Jacuzzi" },
            ],
            about: {
              location: "Malibu Beach Road",
              approval: "CA State Approved",
              type: "Luxury Villa",
              minimumPrice: "$2 Million",
            },
            propertyId: 201,
            type: "Residential",
            propertyFor: "Sale",
            newOrResale: "New",
            tncpApproved: "Yes",
            reraNumber: "RERA1111",
            squareFeet: "5000 sq.ft",
            dimension: "60x90",
            carParking: "5 Covered",
            yearBuilt: "2022",
            facing: "West",
            flooring: "Granite",
            ageOfProperty: "2 years",
            lift: "Yes",
          },
          {
            id: 2,
            link: "https://solverwp.com/demo/react/mingrand/assets/img/product/villa-2.png",
            title: "Villa B",
            description: "Charming Villa in Santorini, Greece",
            price: "$1,800,000",
            status: "Ready to Move",
            propertyDetails: {
              area: "3500 sq.ft",
              configuration: "4 Bedrooms, 4 Bathrooms, 2 Balconies",
              address: "Santorini, Greece",
              floors: "1 Floor",
              possession: "Immediate",
              status: "Available",
              ownership: "Freehold",
              furnishing: "Fully Furnished",
              parking: "3 Covered",
            },
            ownerDetails: {
              name: "Maria Papadopoulos",
              propertiesListed: 4,
              localities: ["Santorini", "Athens"],
              phoneNumber: "9876543214",
            },
            amenities: [
              { label: "Private Pool" },
              { label: "Garden" },
              { label: "Terrace" },
              { label: "Security" },
            ],
            about: {
              location: "Santorini Island",
              approval: "Greece Property Approved",
              type: "Luxury Villa",
              minimumPrice: "$1.5 Million",
            },
            propertyId: 202,
            type: "Residential",
            propertyFor: "Sale",
            newOrResale: "New",
            tncpApproved: "Yes",
            reraNumber: "RERA2222",
            squareFeet: "3500 sq.ft",
            dimension: "50x70",
            carParking: "3 Covered",
            yearBuilt: "2018",
            facing: "South",
            flooring: "Tile",
            ageOfProperty: "6 years",
            lift: "No",
          },
          {
            id: 3,
            link: "https://solverwp.com/demo/react/mingrand/assets/img/product/villa-3.png",
            title: "Villa C",
            description: "Elegant Villa in Dubai, UAE",
            price: "$3,000,000",
            status: "Ready to Move",
            propertyDetails: {
              area: "6000 sq.ft",
              configuration: "7 Bedrooms, 7 Bathrooms, 4 Balconies",
              address: "Dubai, UAE",
              floors: "3 Floors",
              possession: "Immediate",
              status: "Available",
              ownership: "Freehold",
              furnishing: "Fully Furnished",
              parking: "6 Covered",
            },
            ownerDetails: {
              name: "Ahmed Al-Farsi",
              propertiesListed: 6,
              localities: ["Dubai", "Abu Dhabi"],
              phoneNumber: "9876543215",
            },
            amenities: [
              { label: "Private Beach" },
              { label: "Gym" },
              { label: "Spa" },
              { label: "Security" },
            ],
            about: {
              location: "Dubai Marina",
              approval: "Dubai Real Estate Approved",
              type: "Luxury Villa",
              minimumPrice: "$2.5 Million",
            },
            propertyId: 203,
            type: "Residential",
            propertyFor: "Sale",
            newOrResale: "New",
            tncpApproved: "Yes",
            reraNumber: "RERA3333",
            squareFeet: "6000 sq.ft",
            dimension: "70x90",
            carParking: "6 Covered",
            yearBuilt: "2023",
            facing: "East",
            flooring: "Marble",
            ageOfProperty: "1 year",
            lift: "Yes",
          },
        ],
      };
      
    const { category } = useParams(); // Get category from URL params
  
    // Filter properties based on the category
    const filteredProperties = properties[category] || [];
  
    return (
      <div className="p-4">
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
          {filteredProperties.map((property) => (
            <div key={property.id} className="border rounded-lg shadow-md overflow-hidden">
              <img src={property.link} alt={property.title} className="w-full h-48 object-cover" />
              <div className="p-4">
                <h2 className="text-xl font-semibold mb-2">{property.title}</h2>
                <p className="text-gray-600 mb-2">{property.description}</p>
                <p className="text-lg font-bold text-gray-800 mb-2">₹{property.price}</p>
                <p className="text-sm text-gray-500">{property.status}</p>
              </div>
            </div>
          ))}
        </div>
      </div>
    );
  }
  